Instagram/urls.py
from django.urls import path
from . import views

app_name = 'Instagram'

urlpatterns = [
    path('add/', views.AddPic.as_view(), name='add'),
    path('feed/', views.PicView.as_view(), name='feed'),
    path('delete/<image_id>', views.DeletePic.as_view(), name='delete'),
    path('filter/<image_id>', views.AddFilter.as_view(), name='filter'),
    path('comment/<image_id>', views.InsertComment.as_view(), name='comment')
]

MyInsta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('insta/', include('Instagram.urls')),
]

Instagram/models.py
from django.db import models
from django import forms


class Topics(models.Model):
    choice = models.CharField(max_length=8)

    def __str__(self):
        return self.choice


class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    photo = models.ImageField(upload_to='Instagram/static/Instagram/images')
    choosing = models.ForeignKey(Topics, on_delete=models.CASCADE)

    def img_url(self):
        return self.photo.url[len('Instagram/images/'):]


class Comment(models.Model):
    comment = models.CharField(max_length=150)
    document = models.ForeignKey(
        Document, on_delete=models.SET_NULL, blank=True, null=True)

Instagram/forms.py
from django import forms
from .models import Document, Comment
from PIL import ImageFilter


class AddPicForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'photo', 'choosing', )


class DisplayPicForm(forms.Form):
    image = forms.ImageField()


class Filters(forms.Form):
    f_choices = [('', ''), ('BLUR', 'BLUR'), ('CONTOUR', 'CONTOUR'),
                 ('DETAIL', 'DETAIL'), ('EDGE_ENHANCE', 'EDGE_ENHANCE'),
                 ('EDGE_ENHANCE_MORE',
                  'EDGE_ENHANCE_MORE'), ('EMBOSS', 'EMBOSS'), ('FIND_EDGES',
                                                               'FIND_EDGES'),
                 ('SMOOTH', 'SMOOTH'), ('SMOOTH_MORE',
                                        'SMOOTH_MORE'), ('SHARPEN', 'SHARPEN')]
    Choose_A_Filter = forms.ChoiceField(choices=f_choices)

    def apply_filter(self):
        return {
            'BLUR': ImageFilter.BLUR,
            'CONTOUR': ImageFilter.CONTOUR,
            'DETAIL': ImageFilter.DETAIL,
            'EDGE_ENHANCE': ImageFilter.EDGE_ENHANCE,
            'EDGE_ENHANCE_MORE': ImageFilter.EDGE_ENHANCE_MORE,
            'EMBOSS': ImageFilter.EMBOSS,
            'FIND_EDGES': ImageFilter.FIND_EDGES,
            'SMOOTH': ImageFilter.SMOOTH,
            'SMOOTH_MORE': ImageFilter.SMOOTH_MORE,
            'SHARPEN': ImageFilter.SHARPEN
        }.get(self.cleaned_data['Choose_A_Filter'], None)


class CommentForm(forms.Form):
    comment = forms.CharField()

    def __init__(self, document=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.document = document

    def saveComment(self):
        return self.document.comment_set.create(
            comment=self.cleaned_data['comment'])

Instagram/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import HttpResponse
from django.views import View
from django.core.files.storage import FileSystemStorage
from .forms import AddPicForm, Filters, CommentForm
from Instagram import models
from PIL import Image, ImageFilter


def make_obj(picture):
    comments = []
    comment_set = picture.comment_set.all()
    for c in comment_set:
        comments.append(c.comment)
    return {
        'url': picture.photo.url.replace('Instagram/static', ''),
        'description': picture.description,
        'id': picture.id,
        'comments': comments
    }


class PicView(View):
    def get(self, request):
        picture_objects = models.Document.objects.all()
        pictures = []
        for picture in picture_objects:
            pictures.append(make_obj(picture))

        return render(request, 'Instagram/feed.html',
                      {'pictures': pictures,
                       'post_comment': CommentForm()})


class AddPic(View):
    def get(self, request):
        form = AddPicForm(request.POST, request.FILES)
        return render(request, 'Instagram/add.html', {'form': form})

    def post(self, request):
        form = AddPicForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('Instagram:feed')
        else:
            return render(request, 'Instagram/add.html', {'form': form})


class DeletePic(View):
    def post(self, request, image_id):
        models.Document.objects.get(id=image_id).delete()
        return redirect('Instagram:feed')


class AddFilter(View):
    def get(self, request, image_id):
        form = Filters()
        path = 'Instagram/static/' + models.Document.objects.get(
            id=image_id).img_url()
        return render(request, 'Instagram/feed.html', {'form': form})

    def post(self, request, image_id):
        form = Filters(request.POST)
        path = 'Instagram/static/' + models.Document.objects.get(
            id=image_id).img_url()
        image = Image.open(path)
        if form.is_valid():
            f = form.apply_filter()
            image.convert('RGB').filter(f).save(path)
            return redirect('Instagram:feed')
        return render(request, 'Instagram/filter.html', {'form': form})


class InsertComment(View):
    def post(self, request, image_id):
        pic = models.Document.objects.get(id=image_id)
        form = CommentForm(pic, request.POST)
        if form.is_valid():
            form.saveComment()
            return redirect('Instagram:feed')
        else:
            return redirect('Instagram:feed')

Instagram/templates/Instagram/add.html
{% extends 'Instagram/base.html' %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-5">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form.as_p }}
                <button type="submit">Upload</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Instagram/templates/Instagram/base.html
<!DOCTYPE html> {%load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="{% static 'Instagram/style/style.css' %}" rel="stylesheet" type="text/css">
    <title>Instagram</title>
</head>

<body>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {% block content %} 
        {% endblock %}
</body>

</html>

Instagram/templates/Instagram/feed.html
{% extends 'Instagram/base.html' %} {% load static %} {% block content %}

<div class="container">
    <div class="jumbotron">
        <h1>Oz's Photos</h1> 
        <p>Your favorite place to look at images.</p> 
        <form action="{% url 'Instagram:add' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button class="btn" type="submit">
               <strong> ADD A Picture! </strong>
            </button>
        </form>

    </div>
    <div class="row">
    {% if pictures %}
            {% for picture in pictures %}
            <div class="col-lg-3 col-md-6 col-sm-8 col-sm-offset-2 col-lg-offset-0 col-md-offset-0 img-div">
                <img src="{% static picture.url %}?t={% now 'u' %}" >
                <div class="panel panel-warning">
                    <div class="panel-heading">{{ picture.description }} </div>
                    <div class="panel-body">
                        <form action="{% url 'Instagram:delete' picture.id %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <button class="delete" type="submit">
                               <strong> Delete </strong>
                            </button>
                            </form>
                            <form action="{% url 'Instagram:filter' picture.id %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <button class="btn" type="submit">
                                    <strong>Filter </strong>
                            </button>
                            </form>
                            {% if picture.comments %}
                            <h3>
                                <p>{{ picture.choosing }}</p>
                                Comments:
                            </h3>
                                {% for c in picture.comments %}
                                <p>
                                    <div class="comment">
                                    {{ c }}
                                    </div>
                                </p>
                                {% endfor %}
                            {% endif %}
                            <form action="{% url 'Instagram:comment' picture.id %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ post_comment }}
                            <button class="btn" type="submit">Comment</button>
                            </form>        
                    </div>
                  </div>
            </div>
            {% endfor %}
    {% else %}
        <p>No pictures :'(</p>
    {% endif %}
    </div>
</div>
<script src="{% static 'Instagram/style/javascript.js' %}"></script>
{% endblock %}

Instagram/templates/Instagram/filter.html
{% extends 'Instagram/base.html' %} {% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Change! </button>
</form>
{% endblock %}